FROM rust:1.90 as builder

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rust
RUN Cargo build --release
RUN rm -rf src

COPY src ./src
RUN cargo build --release

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates

WORKDIR /app
COPY --from=builder /app/target/release/backend/app/backend

EXPOSE 8080

CMD ["./backend"]

